# Generated by Django 3.1 on 2021-04-24 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'productos'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cat_image',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='producto',
        ),
    ]
