# Generated by Django 3.1 on 2021-04-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20210424_0817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categorias'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='producto',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='category',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='photos/categorias'),
        ),
    ]
